### PR TITLE
Fix bugs in db_create_coverage_table() + new is_used_for_line_up procedure

### LINKED ISSUE #113: Make sure censoring rules are correct
Right now WLD 2017 is not censored, but it should be? 

**EDIT:** Here is what is currently in PovcalNet. 

image

### LINKED ISSUE #116: Differences in regional coverage between PIP and PCN
The result from the regional coverage calculation in `db_create_coverage_table()` does not match the coverage calculation Marta has done for PCN. 

See attached xlsx for identified discrepancies. Highlighted observations where the difference is larger than 2pp and in red those where the difference is >5pp

Largest differences in (comments from Marta S.).:
-	LAC in the 80s and in LAC post 2014 (for the latter, maybe something is happening with Venezuela?)
-	OHI post 2007- in some years you get a 100% coverage which makes me a bit suspicious as we don’t have data on all countries (e.g., New Zealand)
-	MENA in 2002
-	Smaller things that come to my mind: Argentina Rural should be treated as missing country (and same for Suriname)
 
[CoverageTable_Feb22.xlsx](https://github.com/PIP-Technical-Team/pipdm/files/7948671/CoverageTable_Feb22.xlsx)

TO DO: 
- @Aeilert Will create a "a country-year level dataset of coverage from PIP I.e. a dummy variable for each country and each reference year on whether it is covered." 
- @ Marta S /  @danielmahler : Could you add your Stata code to this issue for reference? Might be good to check for potential code differences, in addition to the data inputs. 

cc: @randrescastaneda, @tonyfujs

### PR DESCRIPTION
**Pull request by Aeilert**
Hi @tonyfujs 

Here is a PR for the new `is_used_for_line_up` column and procedure + several fixes for the coverage and censoring calculations. 

For the coverage calculation the following important things have changed: 

* Add SUR as a special country
* Merge with cl_table to ensure that region_code is available for all countries
* Merge with incgrp table to calculate LIC/LMIC coverage

Note that I kept the `*_table()` name for the function and filename for the censoring and coverage functions, even though they now return lists. Partly because we have started moving files to the ingestion repo. But we could change that if you want. 

For the refyear table note the following: 

* `db_create_ref_year_table()` now filters surveys based on the `is_used_for_line_up` column. That means that the predicted mean is only calculated for 1) "normal" national surveys 2) U/R surveys when the "domain" is non-national and 3) urban _or_ rural surveys when there is no national survey  at all for a specific country
* For the rule to create `is_used_for_line_up`  see changes in `db_create_dsm_table()` 
*  `is_used_for_line_up` might not be a perfect name in case it is confused with selection of INC/CON surveys for the line up (but maybe it is good enough) 
* Removed pfw_table from `db_create_ref_year_table()` inputs (no longer used) 

**EDIT:** After taking  a look at the API code and thinking more about this: `is_used_for_line_up` and `is_used_for_aggregation` measure conceptually different things. I thus added a (modified) version of   `is_used_for_aggregation`  back into the output tables. I believe the only surveys that should be aggregated are the ones split by U/R domain (IND, CHN, IDN).  We need to take care that ARG is included in the lineup (meaning `is_used_for_line_up = TRUE` ) now does, but there is no need for any aggregation (`is_used_for_aggregation = FALSE`).

### CODE REVIEW

**Comment by Aeilert** [comment]
In case you want to review the complete flow here, you can use the following script. 
The income group table is pending a PR review in pipaux, but I have attached a version that you can use for now. 

[income_groups.zip](https://github.com/PIP-Technical-Team/pipdm/files/8041022/income_groups.zip)


```r
# Load AUX data
gdp_table <- pipaux::load_aux("gdp") %>% setDT()
pce_table <- pipaux::load_aux("pce") %>% setDT()
pop_table <- pipaux::load_aux("pop") %>% setDT()
ppp_table <- pipaux::load_aux("ppp") %>% setDT()
cpi_table <- pipaux::load_aux("cpi") %>% setDT()
cl_table <- pipaux::load_aux("country_list") %>% setDT()
censored <- pipaux::load_aux("censoring")

# Load incgrp table (new AUX file not implemented yet)
incgrp_table <- readRDS('../pipaux/tmp/income_groups.rds') %>% setDT()

# Load LCU table
f <- "Y:/pip_ingestion_pipeline/pc_data/_targets/objects/svy_mean_lcu_table"
lcu_table <- qs::qread(f)

# Fix ARG 1980 which is incorrectly coded
lcu_table[country_code == "ARG",]$pop_data_level <- "urban"
lcu_table[country_code == "ARG",]$reporting_level <- "urban"

# Create DSM table
dsm_table <- db_create_dsm_table(lcu_table = lcu_table,
                                 cpi_table = cpi_table,
                                 ppp_table = ppp_table)

# Create ref year table
ref_year_table <- db_create_ref_year_table(
  dsm_table = dsm_table,
  gdp_table = gdp_table,
  pce_table = pce_table,
  pop_table = pop_table,
  ref_years = 1981:2021,
  pip_years = 1977:2019
)

# Fix NRU region code
# Inconsistency between PFW and PCN masterfile
ref_year_table[country_code == "NRU",]$pcn_region_code <- "EAP"

# Fix ARG 1980 which is incorrectly coded
ref_year_table[country_code == "ARG",]$pop_data_level <- "urban"
ref_year_table[country_code == "ARG",]$reporting_level <- "urban"

# Create coverage list of tables
coverage_list <- db_create_coverage_table(
  ref_year_table = ref_year_table,
  incgrp_table = incgrp_table,
  cl_table = cl_table,
  pop_table = pop_table,
  ref_years = 1981:2021
)

# Create regional censoring table
db_create_censoring_table(censored = censored,
                          coverage_list = coverage_list,
                          coverage_threshold = 50)
```

File: R/db_create_coverage_table.R [hunk 1]
```diff
@@ -1,21 +1,27 @@
...
 #' @export
 db_create_coverage_table <- function(ref_year_table,
                                      pop_table,
+                                     cl_table,
+                                     incgrp_table,
                                      ref_years,
                                      digits = 2,
                                      special_countries =
-                                       c("ARG", "CHN", "IDN", "IND")) {
+                                       c("ARG", "CHN", "IDN", "IND", "SUR")) {
```
Comment (tonyfujs) [inline R/db_create_coverage_table.R:24]: 2 thougts on this:
1) It may be worth finding a more explicit name. These countries could be special in many ways. Something like `countries_to_include` maybe?
2) We should start removing hard coded values from our codebase, and move it to a dedicated file in the pipeline.

File: R/db_create_coverage_table.R [hunk 2]
```diff
@@ -111,14 +133,33 @@ db_create_coverage_table <- function(ref_year_table,
...
-  # Combine to a single table
-  out <- rbind(out_region, out_wld, out_tot)
+  # Income group coverage
+  out_inc <- dt %>%
+    dplyr::filter(incgroup_historical %in% c("Low income", "Lower middle income")) %>%
+    dplyr::group_by(reporting_year, incgroup_historical) %>%
+    dplyr::summarise(coverage = stats::weighted.mean(coverage, pop)) %>%
+    dplyr::group_by(reporting_year) %>%
+    dplyr::summarise(coverage = mean(coverage)) %>%
+    dplyr::mutate(incgroup_historical = "LIC/LMIC") %>%
```
Comment (tonyfujs) [inline R/db_create_coverage_table.R:143]: What is this for? Just worried about hard coded values...

File: R/db_create_dsm_table.R [hunk 3]
```diff
@@ -122,20 +122,17 @@ db_create_dsm_table <- function(lcu_table,
...
-     by = cache_id
-     ][,
-       # variable for aggregate
-       is_used_for_aggregation := fifelse(n_rl > 1, TRUE, FALSE)
-     ][,
-       # remove counter
-       n_rl := NULL
-     ]
+  dt[, is_used_for_aggregation := ifelse((dt$reporting_level %in% c("urban", "rural") & dt$n_rl == 2), TRUE, FALSE)]
+  dt$n_rl <- NULL
```
Comment (tonyfujs) [inline R/db_create_dsm_table.R:135]: I feel that this code chunk (lines 127 to 132) should live in its own function and be unit tested. This is an important piece of the PIP logic, and it will be easier to manage and document in a self-contained function.

**Review by tonyfujs — CHANGES_REQUESTED** [review]

File: R/db_create_coverage_table.R (hunk 2 above)
Comment (Aeilert) [reply R/db_create_coverage_table.R:143]: I don't think there is any hardcoded values in these four lines of code? The reason we are calculating coverage by historical income groups is because the censoring of WLD year depends on coverage in LIC/LMIC countries, in addition global coverage (this is a "new" rule that was included in PCN in 2021).

**Comment by Aeilert** [comment]
> > * `is_used_for_line_up` might not be a perfect name in case it is confused with selection of INC/CON surveys for the line up (but maybe it is good enough)
> 
> Where is this one implemented? Maybe we should be more explicit about that part of the process...

See https://github.com/PIP-Technical-Team/pipdm/blob/master/R/db_select_lineup_surveys.R

File: R/db_create_coverage_table.R (hunk 1 above)
Comment (Aeilert) [reply R/db_create_coverage_table.R:24]: I agree. These are basically the countries where U/R surveys are used for the line-up and coverage should thus be based on U/R population numbers. Maybe something like `urban_rural_countries` , `non_national_pop_countries` ? 

I also agree with 2) but we don't really have a good system in place for that. I suggest keeping such improvements separate from the current PR.

File: R/db_create_dsm_table.R (hunk 3 above)
Comment (Aeilert) [reply R/db_create_dsm_table.R:135]: Okay. I can try to add a function and corresponding test for this.

Comment (Aeilert) [reply R/db_create_dsm_table.R]: Added. Let me know what you think

File: R/db_create_coverage_table.R (hunk 1 above)
Comment (Aeilert) [reply R/db_create_coverage_table.R]: Renamed to `urban_rural_countries`. Let me know what you think

**Review by tonyfujs — APPROVED** [review]
Thanks @Aeilert 

Looks good to me. One comment though: I haven't been able to run the code you shared with me because of some issue with a pipload dependency. 
image
